### ISSUE TITLE
The redis-py dependency is very old (<=2.10.6)

### ISSUE THREAD

**Issue by yossigo** [RedisLabs/RAMP#45]
This is an almost 4 year old package, any reason the dependency still point to it?
It generates conflicts in newer Python environments.

**Comment by yossigo** [comment]
@swilly22 Do you see a problem with bumping this up? Are there sufficient tests to catch simple redis-py compatibility issues?

**Comment by swilly22** [comment]
I don't see any reason why no to bump redis-py version.

**Comment by yossigo** [comment]
Opened PR #46 and moved discussion there.
