### ISSUE TITLE
Interactive and Command Line modes say "Min rlec version"

### ISSUE THREAD

**Issue by synchrophoto** [RedisLabs/RAMP#5]
Interactive and command line modes ask for "Min rlec version". The product is no longer called RLEC.

Also the minimum the version should default to 5.0, not 5.2

**Comment by swilly22** [comment]
min rlec version -> min redispack version?

**Comment by synchrophoto** [comment]
How about min version in case someone changes their mind again? and then maybe have it in the description where it says "Minimum Redis Enterprise Pack version"? Changing descriptions, later on, is far less intrusive than changing code. Thoughts?

**Comment by swilly22** [comment]
min version isn't a good idea, as the metadata is mostly used to describe a module, e.g. we've got a version attribute.
Thus min_version causes confusion.

**Comment by dvirsky** [comment]
We're removing the interactive mode completely anyway
